[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true }
api = { workspace = true }
queue_core = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
tracing = { workspace = true }
serde_json = { workspace = true }

[features]
server = ["api/server"]
